### ISSUE TITLE
data.table::fread warnings result in errors in read.any

### ISSUE THREAD

**Issue by willdebras** [oliver-wyman-actuarial/easyr#41]
Currently, `read.any` calls a `tryCatch` on reading the file with `data.table::fread` for `.csv` and `.tsv` files that leads to no return statement when data.table warnings occur (only a warning message).

This call will call utils::read.csv as a backup if data.table::fread fails from errors, but it does not return anything in the case of data.table warnings:

```
      tryCatch({
        x <- data.table::fread(filename, sep = ",", 
          header = FALSE, stringsAsFactors = FALSE, 
          encoding = encoding, nrows = nrows)
      }, error = function(e) x <<- utils::read.csv(filename, 
        stringsAsFactors = FALSE, check.names = FALSE, 
        nrows = nrows, header = FALSE, encoding = encoding), 
        warning = function(w) warning("Warning during read of [", 
          filename, "], from data.table::fread \n ", 
          w))
```

In the current control flow, if this has occurred, it hits an error meant to be hit when read.any specifies an invalid file type:

```
  if (is.null(x)) {
    stop("File type may not be acceptable. read.any currently only reads CSV, TSV, XLS, XLSX, DBF, RDS.")
  }
```

Erroring in this case is an issue because often times data.table might print warnings, but resolve them for you. This happens with problems related to quotation, column names, etc. 

Ideally, this function should be updated to print the data.table warnings when this trycatch hits a warning, but still return the read object.

**Comment by brycechamberlain-ow** [comment]
Steps to resolve: 

* Replicate the issue by creating a CSV or TSV file that will cause a warning from data.table::fread. One idea is to create the file such that one of the rows is missing column. You'll need to use text editor to do this. Confirm the warning by reading the file with fread.
* Now read the file with easyr. It should give the warning and then say something like "please use CSV or TSV", which is wrong because you did send a valid file format. 
* Fix the code so that read.any gives the warning but also reads the file. This will involve changing this: `warning = function(w) warning( 'Warning during read of [', filename, '], from data.table::fread \n ', w )` to a function that runs warning() but then also returns the data. It is important that your solution doesn't re-read the file because this will be slow. Google something like "r return expression from trycatch when warning" for potential solutions for doing this. 
* Create a test using the file you created that verifies the solution works. 
*

**Comment by brycechamberlain-ow** [comment]
Resolved with https://github.com/oliver-wyman-actuarial/easyr/pull/49
